name: Rx1st
channels:
  - anaconda
  - https://repo.anaconda.com/pkgs/main/
  - nodefaults
dependencies:
  - python==3.8
  - numpy
  - pandas
  - seaborn
  - tensorflow-gpu==2.4.*
  - matplotlib
  - scikit-learn
  - jupyterlab
  - conda-forge::rdkit==2020.09.3
  - scipy
  - pytorch==1.7.*
  - tqdm