name: Rx1st
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.8
  - numpy
  - pandas
  - seaborn
  - tensorflow==2.4.*
  - matplotlib
  - scikit-learn
  - jupyterlab
  - rdkit==2020.09.3
  - scipy
  - pytorch==1.7.*
  - tqdm